name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.0
      with:
      # Name of the Azure Function App
        app-name: 'mudis-function-demo-one'
      # Path to package or folder. *.zip or a folder to deploy
        #package: # optional, default is .
    
